// Auto-generated by tools/generate_game_pages.py
// Generated on 2025-10-26
const GAMES_DATA = {
    "stunt-simulator-2": {
        "title": "Stunt Simulator 2",
        "slug": "stunt-simulator-2",
        "description": "Play Stunt Simulator 2 free online, unlock ten stunt vehicles, conquer six epic maps, and manage nitro-fueled flips with smooth browser performance.",
        "iframe": "https://unblocked-games.s3.amazonaws.com/games/2021/unity3/stunt-simulator-2/index.html",
        "image": "https://imgs.crazygames.com/stunt-simulator_16x9/20250102034748/stunt-simulator_16x9-cover?metadata=none&quality=75&width=400",
        "category": "stunt",
        "featured": true,
        "keywords": [
            "stunt simulator 2",
            "online stunt game",
            "browser stunt arena",
            "free stunt simulator",
            "car stunt game"
        ]
    },
    "stunt-simulator": {
        "title": "Stunt Simulator",
        "slug": "stunt-simulator",
        "description": "Play the original Stunt Simulator online, swap between ten vehicles, explore sandbox arenas, and perfect loops, drifts, and midair tricks in your browser.",
        "iframe": "https://unblocked-games.s3.amazonaws.com/games/2019/unity3/stunt-simulator/index.html",
        "image": "https://imgs.crazygames.com/stunt-simulator_16x9/20250102034748/stunt-simulator_16x9-cover?metadata=none&quality=75&width=400",
        "category": "stunt",
        "featured": false,
        "keywords": [
            "stunt simulator",
            "stunt simulator classic",
            "browser stunt sandbox",
            "free stunt driving",
            "stunt simulator online"
        ]
    },
    "madalin-stunt-cars-2": {
        "title": "Madalin Stunt Cars 2",
        "slug": "madalin-stunt-cars-2",
        "description": "Drive supercars across Madalin Stunt Cars 2 arenas, conquer loops, mega ramps, and multiplayer lobby races with instant browser play and full stunt freedom.",
        "iframe": "https://www.crazygames.com/embed/madalin-stunt-cars-2",
        "image": "https://imgs.crazygames.com/games/madalin-stunt-cars-2/cover_16x9-1695113654654.png?metadata=none&quality=75&width=400",
        "category": "stunt",
        "featured": true,
        "keywords": [
            "madalin stunt cars 2",
            "stunt sandbox",
            "multiplayer car game",
            "open world racing",
            "browser stunt game"
        ]
    },
    "demolition-derby-3": {
        "title": "Demolition Derby 3",
        "slug": "demolition-derby-3",
        "description": "Smash rivals in Demolition Derby 3, unlock 100 vehicles, wreck across 20 arenas, race online, and enjoy realistic damage modeling directly in your browser.",
        "iframe": "https://www.crazygames.com/embed/demolition-derby-3",
        "image": "https://imgs.crazygames.com/demolition-derby-3_16x9/20250528102730/demolition-derby-3_16x9-cover?metadata=none&quality=75&width=400",
        "category": "demolition",
        "featured": true,
        "keywords": [
            "demolition derby 3",
            "derby game",
            "car destruction",
            "browser demolition derby",
            "online derby racing"
        ]
    },
    "moto-x3m": {
        "title": "Moto X3M",
        "slug": "moto-x3m",
        "description": "Race through loops in Moto X3M, flip dirt bikes across deadly traps, beat every stage timer, and enjoy smooth physics with quick browser play and zero installs.",
        "iframe": "https://www.crazygames.com/embed/moto-x3m",
        "image": "https://imgs.crazygames.com/games/moto-x3m/cover_16x9-1700625476572.png?metadata=none&quality=75&width=400",
        "category": "motorcycle",
        "featured": true,
        "keywords": [
            "moto x3m",
            "bike stunt game",
            "motocross browser",
            "moto x3m online",
            "bike physics game"
        ]
    },
    "moto-x3m-spooky-land": {
        "title": "Moto X3M 6: Spooky Land",
        "slug": "moto-x3m-spooky-land",
        "description": "Blaze through haunted tracks in Moto X3M 6: Spooky Land, dodge skeleton traps, pull death loops, and enjoy Halloween bike chaos with instant browser play.",
        "iframe": "https://www.crazygames.com/embed/moto-x3m-spooky-land",
        "image": "https://imgs.crazygames.com/moto-x3m-spooky-land_16x9/20241128073536/moto-x3m-spooky-land_16x9-cover?metadata=none&quality=75&width=400",
        "category": "motorcycle",
        "featured": false,
        "keywords": [
            "moto x3m 6 spooky land",
            "halloween bike game",
            "moto x3m spooky",
            "bike stunt halloween",
            "browser bike stunts"
        ]
    },
    "crazy-drift": {
        "title": "Crazy Drift",
        "slug": "crazy-drift",
        "description": "Kick tail in Crazy Drift, chain smoky slides across tight arenas, master clutch kicks, and level up drift builds with fast-loading browser sessions.",
        "iframe": "https://www.crazygames.com/embed/crazy-drift",
        "image": "https://imgs.crazygames.com/games/crazy-drift/cover-1655409764442.png?metadata=none&quality=75&width=400",
        "category": "drift",
        "featured": false,
        "keywords": [
            "crazy drift",
            "drift game",
            "browser drift",
            "drift tuning",
            "drift simulator"
        ]
    },
    "rally-racer-dirt": {
        "title": "Rally Racer Dirt",
        "slug": "rally-racer-dirt",
        "description": "Slide gravel stages in Rally Racer Dirt, tune rally cars, perfect Scandinavian flicks, and climb leaderboards across asphalt, snow, and mud with browser play.",
        "iframe": "https://www.crazygames.com/embed/rally-racer-dirt",
        "image": "https://imgs.crazygames.com/rally-racer-dirt_16x9/20250227034748/rally-racer-dirt_16x9-cover?metadata=none&quality=75&width=400",
        "category": "drift",
        "featured": true,
        "keywords": [
            "rally racer dirt",
            "rally drift game",
            "browser rally game",
            "scandinavian flick",
            "online rally racing"
        ]
    },
    "mr-racer-stunt-mania": {
        "title": "MR RACER Stunt Mania",
        "slug": "mr-racer-stunt-mania",
        "description": "Punch nitro through MR RACER Stunt Mania, outrun AI bosses, grind weekly tournaments, and nail blockbuster stunts in a free browser racer built for intensity.",
        "iframe": "https://www.crazygames.com/embed/mr-racer-stunt-mania",
        "image": "https://imgs.crazygames.com/mr-racer-stunt-mania_16x9/20250820054755/mr-racer-stunt-mania_16x9-cover?metadata=none&quality=75&width=400",
        "category": "racing",
        "featured": false,
        "keywords": [
            "mr racer stunt mania",
            "stunt mania game",
            "boss racing",
            "online nitro game",
            "browser stunt racer"
        ]
    },
    "stunt-paradise": {
        "title": "Stunt Paradise",
        "slug": "stunt-paradise",
        "description": "Escape to Stunt Paradise, explore an island of ramps, caverns, and volcano loops, swap cars instantly, and master combo chains while chasing collectibles.",
        "iframe": "https://www.crazygames.com/embed/stunt-paradise",
        "image": "https://imgs.crazygames.com/stunt-paradise_16x9/20250306034851/stunt-paradise_16x9-cover?metadata=none&quality=75&width=400",
        "category": "stunt",
        "featured": false,
        "keywords": [
            "stunt paradise",
            "island stunt game",
            "open world driving",
            "browser car game",
            "free stunt playground"
        ]
    },
    "night-city-racing": {
        "title": "Night City Racing",
        "slug": "night-city-racing",
        "description": "Burn through districts in Night City Racing, unlock hypercars, dominate story duels and multiplayer drifts, and own neon circuits with fast browser play.",
        "iframe": "https://www.crazygames.com/embed/night-city-racing",
        "image": "https://imgs.crazygames.com/night-city-racing/20230127195620/night-city-racing-cover?metadata=none&quality=75&width=400",
        "category": "racing",
        "featured": true,
        "keywords": [
            "night city racing",
            "neon racing game",
            "multiplayer racing",
            "browser street racer",
            "futuristic car game"
        ]
    },
    "gt-cars-mega-ramps": {
        "title": "GT Cars Mega Ramps",
        "slug": "gt-cars-mega-ramps",
        "description": "Scale skyscraper ramps in GT Cars Mega Ramps, launch GT supercars through spiraling jumps, stick precision landings, and chase time trials without downloads.",
        "iframe": "https://www.crazygames.com/embed/gt-cars-mega-ramps",
        "image": "https://imgs.crazygames.com/gt-cars-mega-ramps_16x9/20241106064118/gt-cars-mega-ramps_16x9-cover?metadata=none&quality=75&width=400",
        "category": "stunt",
        "featured": true,
        "keywords": [
            "gt cars mega ramps",
            "mega ramp game",
            "sky racing",
            "online stunt driving",
            "browser racing game"
        ]
    },
    "hyper-cars-ramp-crash": {
        "title": "Hyper Cars Ramp Crash",
        "slug": "hyper-cars-ramp-crash",
        "description": "Fire luxury hypercars off mega ramps in Hyper Cars Ramp Crash, trigger spectacular collisions, analyze damage cams, and enjoy crash physics in your browser.",
        "iframe": "https://www.crazygames.com/embed/hyper-cars-ramp-crash",
        "image": "https://imgs.crazygames.com/hyper-cars-ramp-crash_16x9/20240815092925/hyper-cars-ramp-crash_16x9-cover?metadata=none&quality=75&width=400",
        "category": "demolition",
        "featured": false,
        "keywords": [
            "hyper cars ramp crash",
            "car crash simulator",
            "mega ramp crash",
            "browser crash game",
            "hypercar destruction"
        ]
    }
};

const CATEGORIES = {
    "stunt": {
        "name": "Stunt Games",
        "icon": "🎯",
        "description": "Extreme stunt games with incredible jumps and aerial maneuvers"
    },
    "racing": {
        "name": "Racing Games",
        "icon": "🏁",
        "description": "High-speed racing games with competitive action"
    },
    "drift": {
        "name": "Drift Games",
        "icon": "💨",
        "description": "Master the art of drifting with precision control"
    },
    "motorcycle": {
        "name": "Motorcycle Games",
        "icon": "🏍️",
        "description": "Two-wheeled action with backflips and tricks"
    },
    "demolition": {
        "name": "Demolition Games",
        "icon": "💥",
        "description": "Crash and destroy without consequences"
    }
};

function getGameBySlug(slug) {
    return GAMES_DATA[slug];
}

function getGamesByCategory(category) {
    return Object.values(GAMES_DATA).filter(game => game.category === category);
}

function getFeaturedGames() {
    return Object.values(GAMES_DATA).filter(game => game.featured);
}

function getAllGames() {
    return Object.values(GAMES_DATA);
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { GAMES_DATA, CATEGORIES, getGameBySlug, getGamesByCategory, getFeaturedGames, getAllGames };
}
